#
# Blog settings
#
sitename: Brad Westness.com
baseurl: http://www.bradwestness.com/
logo: content/images/kuub.jpg
description: Brewers baseball, .NET software development, pop culture, etc.

#
# Jekyll settings
#
permalink: pretty
paginate: 3
paginate_path: "page/:num"

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

feed:
  path: atom.xml