#
# Blog settings
#
sitename: Brad Westness
baseurl: https://brad.westness.cc/
logo: content/images/caricature.jpg
description: Wisconsinite, .NET software engineer, Brewers baseball fan, he/him
keywords: .NET,Software,Programming,Development,Wisconsin,Brewers,Baseball,Movies,Music

#
# Jekyll settings
#
permalink: /:year/:month/:day/:title/
paginate: 3
paginate_path: "page/:num"
category_dir: categories
timezone: America/Chicago

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

feed:
  path: atom.xml

include: [".well-known"]
