#
# Blog settings
#
sitename: Brad Westness.com
baseurl: http://www.bradwestness.com/
logo: content/images/kuub.jpg
description: .NET software development, Brewers baseball, pop culture, etc.

#
# Jekyll settings
#
permalink: /:year/:month/:day/:title/
paginate: 3
paginate_path: "page/:num"
category_dir: categories
timezone: America/Chicago

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

feed:
  path: atom.xml