#
# Blog settings
#
sitename: Brad Westness.com
baseurl: http://www.bradwestness.com/
logo: content/images/dip.jpg
description: Toiling in transistor soil.

#
# Jekyll settings
#
permalink: pretty
paginate: 3
paginate_path: "page/:num"

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
