destination: ./_site
lsi:         false
port:        4000
highligher:  true
markdown:    rdiscount
permalink:   /archive/:year/:month/:day/:title/
baseurl: http://www.bradwestness.com/
paginate: 3
paginate_path: "page/:num"
rdiscount:
  extensions: [smart]
