#
# Blog settings
#
sitename: Brad Westness.com
baseurl: https://www.bradwestness.com/
logo: content/images/brick.jpg
description: .NET software development, Brewers baseball, pop culture, etc.
keywords: .NET,Software,Programming,Development,Brewers,Baseball,Movies,Music

#
# Jekyll settings
#
permalink: /:year/:month/:day/:title/
paginate: 3
paginate_path: "page/:num"
category_dir: categories
timezone: America/Chicago

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

feed:
  path: atom.xml