destination: ./_site
lsi:         false
port:        4000
highligher:  true
markdown:    rdiscount
permalink:   /:year/:month/:day/:title/
baseurl: http://www.bradwestness.com/
paginate: 3
paginate_path: "/archive/:num/"
rdiscount:
  extensions: [smart]
