#
# Blog settings
#
baseurl: http://www.bradwestness.com/
description: A simple man in complex times.

#
# Jekyll settings
#
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
permalink: pretty
paginate: 3
paginate_path: "page/:num"

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
